### PR TITLE
done the running and adjusted some wordings

### PR DESCRIPTION
**Pull request by JohnShiuMK**

### CODE REVIEW

**Comment by zgarciaj** [comment]
Line: "job, education, contact and poutcome contain unknown values, but they could be kept, because our task is to find out the importance of features. There should be no harm to keep it, but we would expect the result to tell me that this contact is not important."  

Question: given that "job, education, and contact" all appear to have unknowns but not ´too many´, should the last line be - we would expect the result to tell us job, education, and contact do not rank high in importance. Or should we make a distinction as to why we are singling out "contact" on the last line?

Consistency: It is worded on the report like this = "The features job and education, and contact are also worth retaining in the analysis. Although they contain "unknown" values, their proportion is not significantly high. Furthermore, our objective is to unveil the relevance of each feature. Keeping these variables allows for a comprehensive analysis, even though we might anticipate the outcome to suggest that these features are not of high importance."

**Comment by zgarciaj** [comment]
Change has been made on report file. The edit is no longer needed! The branch is ready for merge!

**Comment by zgarciaj** [comment]
Changes have been made on the report file and there will be a specification edit on the analysis file. After that we are ready to 🚀🚀🚀🚀

**Comment by JohnShiuMK** [comment]
done, have specified the reasoning of the expectation on the `contact`, thanks!

**Pull request merged**
